version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teahan-sound-web
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - teahan-net

  nginx:
    image: nginx:1.27-alpine
    container_name: teahan-sound-nginx
    restart: unless-stopped
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - teahan-net

networks:
  teahan-net:
    driver: bridge
