version: '3.9'
services:
  web:
    build: .
    container_name: teahan-sound-web
    restart: unless-stopped
    env_file: .env
    networks:
      - teahan-net

  nginx:
    image: nginx:1.27-alpine
    container_name: teahan-sound-nginx
    restart: unless-stopped
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9191:80"
    networks:
      - teahan-net

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: teahan-sound-mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"  # Web UI
    networks:
      - teahan-net

networks:
  teahan-net:
    driver: bridge
